--- 
orbs: ~
version: 2.1
workflows: 
  main: 
    jobs: 
      docker: 
        - 
          image: "circleci/node:8"
        - 
          run: 
            build: 
              - 
                run: 
                  command: "\"react-native start\""
                  name: "fastlane adhoc android"
                  working_directory: android
            name: android
            requires: 
              - node
  version: 2
