before_script:
  - export ANDROID_HOME="/Users/admin/Library/Android/sdk"

version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: cd android && ./gradlew assembleRelease --stacktrace

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
