version: 2.1
orbs:
workflows:
  version: 2
  main:
    jobs:
      docker:
      - image: circleci/node:8
          name: android
          requires:
            - node
          build:
            - run:
                name: fastlane adhoc android
                working_directory: android
                command: |
                  "react-native start"
