--- 
jobs: 
  android: 
    docker: 
      - 
        image: "circleci/android:api-27-node8-alpha"
    steps: 
      - 
        checkout: 
          path: ~/DemoCircleCI
      - 
        attach_workspace: 
          at: ~/DemoCircleCI
      - 
        run: "bundle install"
      - 
        run: 
          command: 
            - "react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/"
            - "cd android && ./gradlew assembleRelease --stacktrace"
            - "cd .."
            - "mv android/app/build/outputs/apk/release/app-universal-release.apk ANDROID_DEV_v${CI_BUILD_ID}.apk"
          name: "fastlane tests"
    working_directory: ~/DemoCircleCI/android
  node: 
    docker: 
      - 
        image: "circleci/node:8"
    steps: 
      - 
        run: "yarn install"
      - 
        save_cache: 
          key: "yarn-v1-{{ checksum \"yarn.lock\" }}-{{ arch }}"
          paths: 
            - ~/.cache/yarn
      - 
        save_cache: 
          key: "node-v1-{{ checksum \"package.json\" }}-{{ arch }}"
          paths: 
            - node_modules
      - 
        run: 
          command: |
              mkdir -p test-results/jest
              yarn run test
          name: "jest tests"
      - 
        persist_to_workspace: 
          paths: 
            - node_modules
          root: ~/DemoCircleCI
    working_directory: ~/DemoCircleCI
version: 2.1
workflows: 
  node-android-ios: 
    jobs: 
      - node
      - 
        android: 
          requires: 
            - node
  version: 2.1
