--- 
  version: 2
jobs: 
  android: 
    docker: 
      - image: "circleci/android:api-27-node8-alpha"
      - image: "circleci/node:8"
    working_directory: ~/DemoCircleCI
    steps: 
      - 
        checkout: 
          path: ~/DemoCircleCI
      - 
        attach_workspace: 
          at: ~/DemoCircleCI
      - 
        run: "bundle install"
      - run: "yarn install"
      - 
        run: 
          command: 
            - "react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/"
            - "cd android && ./gradlew assembleRelease --stacktrace"
            - "cd .."
            - "mv android/app/build/outputs/apk/release/app-universal-release.apk ANDROID_DEV_v${CI_BUILD_ID}.apk"
          name: "fastlane tests"
          
          workflows:
  version: 2
  node-android-ios:
    jobs:
      - android:
          requires:
            - node
