# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  node:
    working_directory: ~/DemoCircleCI
    docker:
      - image: circleci/node:8
    steps:

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test


      - persist_to_workspace:
          root: ~/DemoCircleCI
          paths:
            - node_modules

  android:
    working_directory: ~/DemoCircleCI/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/DemoCircleCI

      - attach_workspace:
          at: ~/DemoCircleCI

      - run: bundle install

      - run:
          name: fastlane tests
          command: |
          react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
          cd android && ./gradlew assembleRelease --stacktrace
          cd ..
          mv android/app/build/outputs/apk/release/app-universal-release.apk ANDROID_DEV_v${CI_BUILD_ID}.apk
workflows:
  version: 2.1
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node


