version: 2.1
orbs:
- image: circleci/node:8
workflows:
  version: 2
  main:
    jobs:
      - react-native/node:
          name: node
      - react-native/android:
          name: android
          requires:
            - node
          build:
            - run:
                name: fastlane adhoc android
                working_directory: android
                command: |
                  "react-native start"
      - react-native/ios:
          name: ios
          requires:
            - node
          build:
            - run:
                name: fastlane adhoc ios
                working_directory: ios
                command: |
                  "react-native start"
